const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const ts = require('typescript')
const cache = {}
function load(name) {
    const file = path.resolve(__dirname, '../lib', name + '.ts')
    if (cache[file]) return cache[file]
    const exports = {}; cache[file] = exports
    const js = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } }).outputText
    new Function('exports', 'require', js)(exports, id => id.endsWith('.json') ? require(path.resolve(path.dirname(file), id)) : load(path.basename(id)))
    return exports
}
const comic = load('stdComic'), policy = load('stdPolicy'), steps = load('stdProjectStepStatus')
const characterThumbnails = load('stdCharacterThumbnail')
const { balloonPopScale } = load('stdComicLettering')
assert.equal(balloonPopScale(0), .72)
assert.equal(balloonPopScale(.36), 1)
assert.equal(balloonPopScale(2), 1)
assert.ok(balloonPopScale(.198) > balloonPopScale(.2808))
for(let i=0;i<=100;i++)assert.ok(balloonPopScale(i*.0036)>=.72 && balloonPopScale(i*.0036)<=1)
const standard = { project_payload: {} }
const book = { project_payload: {render_settings: {comic: {version: 1, mode: 'comic'}}} }
assert.equal(comic.isComicProject(standard), false)
assert.equal(comic.isComicProject({project_payload:{render_settings:{comic:{mode:'comic'}}}}), false)
assert.equal(policy.isStdRequiredVideoScene(1, standard), true)
assert.equal(policy.isStdRequiredVideoScene(13, standard), true)
assert.equal(policy.isStdRequiredClipScene(12, standard), true)
assert.equal(policy.isStdRequiredClipScene(13, standard), true)
assert.equal(policy.isStdRequiredClipScene(18, standard), true)
assert.equal(policy.isStdRequiredClipScene(19, standard), false)
assert.equal(policy.isStdVideoPromptScene(18, standard), true)
assert.equal(policy.isStdMiddleVideoScene(13, standard), true)
assert.equal(policy.isStdMiddleVideoScene(18, standard), true)
assert.equal(policy.isStdMiddleVideoScene(19, standard), false)
const configuredVideoRange = { project_payload: { structure: { required_video_scene_count: 24 } } }
assert.equal(policy.stdRequiredVideoSceneCount(configuredVideoRange), 24)
assert.equal(policy.isStdRequiredClipScene(24, configuredVideoRange), true)
assert.equal(policy.isStdRequiredClipScene(25, configuredVideoRange), false)
assert.equal(policy.stdRequiredVideoSceneCount({ required_video_scene_count: null, video_scenes: 22 }), 22)
assert.equal(policy.isStdRequiredVideoScene(1, book), false)
assert.deepEqual(characterThumbnails.gcsCharacterObjectFromUrl('/api/std/assets/gcs-file?bucket=air-studio-prod&path=topics%2F3373%2Fcharacters%2Fcodex-main.png', 'https://studio.example'), { bucket: 'air-studio-prod', path: 'topics/3373/characters/codex-main.png' })
assert.deepEqual(characterThumbnails.gcsCharacterObjectFromUrl('/api/std/assets/gcs-file?bucket=air-studio-prod&path=topics%2Fprepared%2FBp8mgsjeeEo%2Fcharacters%2Fotsumu-132cea89d120b950.png', 'https://studio.example'), { bucket: 'air-studio-prod', path: 'topics/prepared/Bp8mgsjeeEo/characters/otsumu-132cea89d120b950.png' })
assert.deepEqual(characterThumbnails.gcsCharacterObjectFromUrl('/api/std/assets/gcs-file?bucket=air-studio-prod&path=topics%2F3377%2Fcharacters%2Frecurring-character-designs-20261003%2Fshoya.png', 'https://studio.example'), { bucket: 'air-studio-prod', path: 'topics/3377/characters/recurring-character-designs-20261003/shoya.png' })
assert.equal(characterThumbnails.gcsCharacterObjectFromUrl('https://elsewhere.example/api/std/assets/gcs-file?bucket=air-studio-prod&path=topics%2F3373%2Fcharacters%2Fcodex-main.png', 'https://studio.example'), null)
assert.equal(characterThumbnails.gcsCharacterObjectFromUrl('/api/std/assets/gcs-file?bucket=air-studio-prod&path=private%2Fsecret.png', 'https://studio.example'), null)
assert.equal(characterThumbnails.gcsCharacterObjectFromUrl('/api/std/assets/gcs-file?bucket=air-studio-prod&path=topics%2Fprepared%2Fx%2Fcharacters%2F..%2Fsecret.png', 'https://studio.example'), null)
assert.equal(characterThumbnails.characterImageContentType('topics/3373/characters/a.webp'), 'image/webp')
assert.equal(policy.isStdRequiredVideoScene(1), true)
assert.equal(comic.selectComicMedia('comic', 'image', 'video'), 'image')
assert.equal(comic.selectComicMedia('moving_comic', 'image', 'video'), 'video')
assert.equal(comic.selectComicMedia('standard', 'image', 'video'), 'video')
assert.equal(comic.selectComicMedia('comic', undefined, 'video'), 'video')
const cfg = comic.normalizeComicSettings({version:1, mode:'comic', layout:'__proto__', turn_duration:Infinity})
assert.equal(cfg.layout, 'spread'); assert.equal(cfg.turn_duration, .7)
assert.deepEqual(comic.comicPages([1,2,3], cfg), [[1,2],[3]])
const imgProject = {...book, project_payload: {...book.project_payload, scenes:[{scene_number:1,image_url:'image.png'}]}}
assert.equal(steps.summarizeStdProject(imgProject).isImageDone, true)
assert.equal(steps.summarizeStdProject({...imgProject, project_payload:{...imgProject.project_payload,render_settings:{}}}).isImageDone, false)
const scenesThrough18 = Array.from({length:19}, (_, i) => ({scene_number:i+1, image_url:`image-${i+1}.png`}))
assert.equal(steps.summarizeStdProject({project_payload:{scenes:scenesThrough18}}).isImageDone, false)
scenesThrough18.forEach((scene, index) => { if (index < 18) scene.video_url = `video-${index+1}.mp4` })
assert.equal(steps.summarizeStdProject({project_payload:{scenes:scenesThrough18}}).isImageDone, true)
const times = comic.comicSceneTimings([{scene_number:1},{scene_number:2}], [{scene_number:1,start_time:0,end_time:2,text:'a'},{scene_number:2,start_time:2,end_time:4,text:'b'}])
assert.deepEqual(times.map(t=>[t.start,t.end]), [[0,2],[2,4]])
console.log('PASS: required clips through scene 18, project readiness, media priority, page grouping, timing')

const mixed=comic.normalizeComicSettings({version:1,mode:'moving_comic',layout:'grid',page_layouts:{0:'single',1:'wide',2:'grid6'},lettering:{'1:0':{kind:'dialogue',style:'shout',x:.3,y:.2,width:.4,target_x:.8,target_y:.6}}})
assert.deepEqual(comic.comicPages([1,2,3,4,5,6,7,8,9],mixed),[[1],[2,3],[4,5,6,7,8,9]])
assert.equal(mixed.lettering['1:0'].style,'shout')
assert.equal(comic.normalizeComicSettings(mixed).lettering['1:0'].x,.3)
assert.equal(comic.normalizeComicSettings({lettering:{'bad':{x:0},'1:0':{width:999,x:-2}}}).lettering['1:0'].width,.94)
const outline=load('stdComicLettering').balloonOutline(100,100,200,100,'dialogue','speech',420,150)
assert.equal(outline.length,82)
assert.ok(outline[0][0]<300 && outline[80][0]<300)
assert.ok(outline[81][0]>300)
console.log('PASS: mixed layouts, lettering persistence, continuous tail outline')
assert.equal(comic.normalizeComicSettings({panels:{1:{fit:'cover'}}}).panels['1'].motion, undefined)
assert.equal(comic.normalizeComicSettings({panels:{1:{motion:'still'}}}).panels['1'].motion, 'still')
const planned = {project_payload:{structure:{comic_plan:{render_settings:{...mixed,panels:{13:{motion:'pan',fit:'cover'},14:{motion:'still'}}}}}}}
const uploaded = comic.comicSettingsWithUploadedVideo(planned,13)
assert.equal(uploaded.panels['13'].motion,'video')
assert.equal(uploaded.panels['13'].fit,'cover')
assert.equal(uploaded.panels['14'].motion,'still')
assert.deepEqual(uploaded.page_layouts,mixed.page_layouts)
assert.equal(planned.project_payload.structure.comic_plan.render_settings.panels['13'].motion,'pan')
assert.equal(comic.comicSettingsWithUploadedVideo(standard,13).mode,'standard')
assert.equal(comic.selectComicMedia(uploaded.mode,'scene.png','uploaded.mp4'),'uploaded.mp4')
console.log('PASS: manual clip upload overrides planned pan without altering other scenes or layouts')
