-- migration: air_0161b_referral_dashboard_rpcs.sql

-- 1. Create necessary indexes
CREATE INDEX IF NOT EXISTS idx_commissions_user_status_created ON public.commissions(user_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_profiles_referrer_id ON public.profiles(referrer_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_reqs_user_created ON public.withdrawal_requests(user_id, created_at DESC);

-- 2. Drop existing functions if they exist (for safe recreation)
DROP FUNCTION IF EXISTS get_referral_dashboard_kpi(UUID);
DROP FUNCTION IF EXISTS get_referral_tree(UUID, INT);
DROP FUNCTION IF EXISTS get_commission_timeline(UUID, INT, INT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT);

-- 3. get_referral_dashboard_kpi
CREATE OR REPLACE FUNCTION get_referral_dashboard_kpi(p_user_id UUID)
RETURNS JSONB
SECURITY DEFINER
AS $$
DECLARE
    v_total_referrals INT := 0;
    v_level1_count INT := 0;
    v_level2_count INT := 0;
    v_active_members INT := 0;
    v_inactive_members INT := 0;
    v_today_commission NUMERIC := 0;
    v_month_commission NUMERIC := 0;
    v_pending_commission NUMERIC := 0;
    v_approved_commission NUMERIC := 0;
    v_withdrawable_balance NUMERIC := 0;
    v_withdrawn_total NUMERIC := 0;
    v_locked_withdrawals NUMERIC := 0;
    v_total_downline_jobs INT := 0;
    v_total_downline_commissions NUMERIC := 0;
    v_average_jobs_per_member NUMERIC := 0;
    v_average_commission_per_member NUMERIC := 0;
    v_expected_month_commission NUMERIC := 0;
    v_forecast_next_payout NUMERIC := 0;
    v_organization_health_score INT := 0;
    v_organization_health_grade TEXT := 'Dormant';
    v_notifications JSONB := '[]'::JSONB;
    
    v_today DATE := CURRENT_DATE;
    v_month_start DATE := date_trunc('month', CURRENT_DATE);
    v_days_in_month INT := extract(days from (date_trunc('month', CURRENT_DATE) + interval '1 month - 1 day'));
    v_day_of_month INT := extract(day from CURRENT_DATE);
BEGIN
    -- Security Validation
    IF auth.uid() != p_user_id THEN
        RAISE EXCEPTION 'Unauthorized: p_user_id does not match auth.uid()';
    END IF;

    -- CTE to get all descendants up to level 10 (reasonable max for now)
    WITH RECURSIVE downline AS (
        SELECT id, referrer_id, 1 AS level, last_sign_in_at
        FROM public.profiles
        WHERE referrer_id = p_user_id
        
        UNION ALL
        
        SELECT p.id, p.referrer_id, d.level + 1, p.last_sign_in_at
        FROM public.profiles p
        INNER JOIN downline d ON p.referrer_id = d.id
        WHERE d.level < 10
    )
    SELECT 
        COUNT(*),
        COUNT(*) FILTER (WHERE level = 1),
        COUNT(*) FILTER (WHERE level = 2),
        COUNT(*) FILTER (WHERE last_sign_in_at >= CURRENT_DATE - INTERVAL '7 days'),
        COUNT(*) FILTER (WHERE last_sign_in_at < CURRENT_DATE - INTERVAL '7 days' OR last_sign_in_at IS NULL)
    INTO 
        v_total_referrals, v_level1_count, v_level2_count, v_active_members, v_inactive_members
    FROM downline;

    -- User's Commission KPIs
    SELECT 
        COALESCE(SUM(amount) FILTER (WHERE created_at >= v_today::timestamp AND status = 'APPROVED'), 0),
        COALESCE(SUM(amount) FILTER (WHERE created_at >= v_month_start::timestamp AND status = 'APPROVED'), 0),
        COALESCE(SUM(amount) FILTER (WHERE status = 'PENDING'), 0),
        COALESCE(SUM(amount) FILTER (WHERE status = 'APPROVED'), 0)
    INTO 
        v_today_commission, v_month_commission, v_pending_commission, v_approved_commission
    FROM public.commissions
    WHERE user_id = p_user_id;

    -- User's Withdrawal KPIs
    SELECT 
        COALESCE(SUM(amount) FILTER (WHERE status IN ('REQUESTED', 'APPROVED', 'SENDING', 'COMPLETED')), 0),
        COALESCE(SUM(amount) FILTER (WHERE status = 'COMPLETED'), 0)
    INTO 
        v_locked_withdrawals, v_withdrawn_total
    FROM public.withdrawal_requests
    WHERE user_id = p_user_id;

    v_withdrawable_balance := v_approved_commission - v_locked_withdrawals;

    -- Downline averages (Jobs and Commissions generated by the downline)
    SELECT COALESCE(COUNT(*), 0), COALESCE(SUM(amount), 0)
    INTO v_total_downline_jobs, v_total_downline_commissions
    FROM public.commissions c
    WHERE c.user_id IN (SELECT id FROM public.profiles WHERE referrer_id = p_user_id) 
      AND c.created_at >= v_month_start::timestamp;

    IF v_active_members > 0 THEN
        v_average_jobs_per_member := ROUND((v_total_downline_jobs::numeric / v_active_members), 1);
        v_average_commission_per_member := ROUND((v_total_downline_commissions / v_active_members), 2);
    END IF;

    -- Forecasting
    IF v_day_of_month > 0 THEN
        v_expected_month_commission := ROUND((v_month_commission / v_day_of_month) * v_days_in_month, 2);
    END IF;
    v_forecast_next_payout := v_withdrawable_balance + v_pending_commission;

    -- Organization Health Calculation
    -- Score out of 100 based on active members ratio and recent growth
    IF v_total_referrals > 0 THEN
        v_organization_health_score := ROUND((v_active_members::numeric / v_total_referrals::numeric) * 100);
    ELSE
        v_organization_health_score := 0;
    END IF;

    IF v_organization_health_score >= 90 THEN v_organization_health_grade := 'Excellent';
    ELSIF v_organization_health_score >= 70 THEN v_organization_health_grade := 'Healthy';
    ELSIF v_organization_health_score >= 40 THEN v_organization_health_grade := 'Warning';
    ELSE v_organization_health_grade := 'Critical';
    END IF;

    RETURN jsonb_build_object(
        'total_referrals', v_total_referrals,
        'level1_count', v_level1_count,
        'level2_count', v_level2_count,
        'organization_size', v_total_referrals,
        'active_members', v_active_members,
        'inactive_members', v_inactive_members,
        'today_commission', v_today_commission,
        'month_commission', v_month_commission,
        'pending_commission', v_pending_commission,
        'approved_commission', v_approved_commission,
        'withdrawable_balance', v_withdrawable_balance,
        'withdrawn_total', v_withdrawn_total,
        'expected_month_commission', v_expected_month_commission,
        'forecast_next_payout', v_forecast_next_payout,
        'organization_health_score', v_organization_health_score,
        'organization_health_grade', v_organization_health_grade,
        'notifications', v_notifications
    );
END;
$$ LANGUAGE plpgsql;


-- 4. get_referral_tree
CREATE OR REPLACE FUNCTION get_referral_tree(p_user_id UUID, p_max_level INT DEFAULT 100)
RETURNS JSONB
SECURITY DEFINER
AS $$
DECLARE
    v_result JSONB;
BEGIN
    -- Security Validation
    IF auth.uid() != p_user_id THEN
        RAISE EXCEPTION 'Unauthorized: p_user_id does not match auth.uid()';
    END IF;

    WITH RECURSIVE downline AS (
        SELECT 
            p.id, 
            p.email as username,
            p.email as display_name,
            '' as avatar_url,
            p.referrer_id, 
            1 AS level, 
            p.created_at as joined_at,
            p.last_sign_in_at as last_login,
            'ACTIVE' as status
        FROM public.profiles p
        WHERE p.referrer_id = p_user_id
        
        UNION ALL
        
        SELECT 
            p.id, 
            p.email as username,
            p.email as display_name,
            '' as avatar_url,
            p.referrer_id, 
            d.level + 1, 
            p.created_at as joined_at,
            p.last_sign_in_at as last_login,
            'ACTIVE' as status
        FROM public.profiles p
        INNER JOIN downline d ON p.referrer_id = d.id
        WHERE d.level < p_max_level
    ),
    tree_with_stats AS (
        SELECT 
            d.id as user_id,
            d.username,
            d.display_name,
            d.avatar_url,
            d.referrer_id as parent_id,
            d.level,
            CASE 
                WHEN d.last_login >= CURRENT_DATE - INTERVAL '7 days' THEN 'ACTIVE'
                ELSE 'INACTIVE'
            END as status,
            d.joined_at,
            d.last_login,
            COALESCE(d.last_login, d.joined_at) as last_activity,
            
            (SELECT COUNT(*) FROM public.commissions WHERE user_id = d.id AND created_at >= CURRENT_DATE::timestamp) as today_jobs,
            (SELECT COUNT(*) FROM public.commissions WHERE user_id = d.id AND created_at >= date_trunc('month', CURRENT_DATE)::timestamp) as month_jobs,
            (SELECT COALESCE(SUM(amount), 0) FROM public.commissions WHERE user_id = d.id AND created_at >= CURRENT_DATE::timestamp) as today_commission,
            (SELECT COALESCE(SUM(amount), 0) FROM public.commissions WHERE user_id = d.id AND created_at >= date_trunc('month', CURRENT_DATE)::timestamp) as month_commission,
            (SELECT COALESCE(SUM(amount), 0) FROM public.commissions WHERE user_id = d.id AND status = 'APPROVED') as total_commission,
            
            -- Simplified withdrawable balance for tree nodes
            ((SELECT COALESCE(SUM(amount), 0) FROM public.commissions WHERE user_id = d.id AND status = 'APPROVED') - 
             (SELECT COALESCE(SUM(amount), 0) FROM public.withdrawal_requests WHERE user_id = d.id AND status IN ('REQUESTED', 'APPROVED', 'SENDING', 'COMPLETED'))) as withdrawable_balance,
            
            (SELECT COUNT(*) FROM public.profiles WHERE referrer_id = d.id) as children_count,
            (SELECT COUNT(*) FROM public.profiles WHERE referrer_id = d.id AND last_sign_in_at >= CURRENT_DATE - INTERVAL '7 days') as active_children
            
        FROM downline d
    ),
    tree_with_scores AS (
        SELECT 
            t.*,
            -- Scoring logic
            LEAST(10, CASE WHEN t.last_login >= CURRENT_DATE - INTERVAL '7 days' THEN 10 ELSE 0 END) as login_score,
            LEAST(30, (t.month_jobs * 2)) as job_score,
            LEAST(35, (t.month_commission * 5)::INT) as commission_score,
            LEAST(25, (t.active_children * 5)) as referral_score
        FROM tree_with_stats t
    )
    SELECT COALESCE(jsonb_agg(
        jsonb_build_object(
            'user_id', user_id,
            'username', username,
            'display_name', display_name,
            'avatar_url', avatar_url,
            'parent_id', parent_id,
            'level', level,
            'status', status,
            'joined_at', joined_at,
            'last_login', last_login,
            'last_activity', last_activity,
            'today_jobs', today_jobs,
            'month_jobs', month_jobs,
            'today_commission', today_commission,
            'month_commission', month_commission,
            'total_commission', total_commission,
            'withdrawable_balance', withdrawable_balance,
            'children_count', children_count,
            'active_children', active_children,
            'contribution', jsonb_build_object(
                'score', (login_score + job_score + commission_score + referral_score),
                'grade', CASE 
                    WHEN (login_score + job_score + commission_score + referral_score) >= 80 THEN 'Leader'
                    WHEN (login_score + job_score + commission_score + referral_score) >= 50 THEN 'Active'
                    WHEN (login_score + job_score + commission_score + referral_score) >= 20 THEN 'Growing'
                    ELSE 'Dormant'
                END,
                'login_score', login_score,
                'job_score', job_score,
                'commission_score', commission_score,
                'referral_score', referral_score
            )
        )
    ), '[]'::jsonb)
    INTO v_result
    FROM tree_with_scores;

    RETURN v_result;
END;
$$ LANGUAGE plpgsql;


-- 5. get_commission_timeline
CREATE OR REPLACE FUNCTION get_commission_timeline(
    p_user_id UUID, 
    p_limit INT DEFAULT 50, 
    p_offset INT DEFAULT 0,
    p_type TEXT DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_date_from TEXT DEFAULT NULL,
    p_date_to TEXT DEFAULT NULL,
    p_sort_by TEXT DEFAULT 'created_at',
    p_sort_dir TEXT DEFAULT 'desc'
)
RETURNS JSONB
SECURITY DEFINER
AS $$
DECLARE
    v_result JSONB;
    v_total_records INT := 0;
BEGIN
    -- Security Validation
    IF auth.uid() != p_user_id THEN
        RAISE EXCEPTION 'Unauthorized: p_user_id does not match auth.uid()';
    END IF;

    -- Using a temp table or common approach to union and paginate
    -- Since we need total records for pagination, we count first
    
    WITH combined_timeline AS (
        SELECT 
            id::text,
            'COMMISSION' as type,
            created_at as date,
            NULL::uuid as member_id, -- Can join if needed later
            job_type,
            job_type as job_title,
            amount,
            status,
            created_at,
            created_at as approved_at,
            created_at as withdrawable_at,
            NULL::timestamp as withdrawn_at
        FROM public.commissions
        WHERE user_id = p_user_id

        UNION ALL

        SELECT 
            id::text,
            'WITHDRAWAL' as type,
            created_at as date,
            NULL::uuid as member_id,
            NULL as job_type,
            'Withdrawal Request' as job_title,
            -amount as amount,
            status,
            created_at,
            approved_at,
            NULL as withdrawable_at,
            completed_at as withdrawn_at
        FROM public.withdrawal_requests
        WHERE user_id = p_user_id
    ),
    filtered_timeline AS (
        SELECT * FROM combined_timeline
        WHERE (p_type IS NULL OR type = p_type)
          AND (p_status IS NULL OR status = p_status)
          AND (p_date_from IS NULL OR created_at >= p_date_from::timestamp)
          AND (p_date_to IS NULL OR created_at <= p_date_to::timestamp)
    )
    SELECT COUNT(*) INTO v_total_records FROM filtered_timeline;

    -- Fetch paginated
    WITH combined_timeline AS (
        SELECT 
            id::text,
            'COMMISSION' as type,
            created_at as date,
            NULL::uuid as member_id, 
            job_type,
            job_type as job_title,
            amount,
            status,
            created_at,
            created_at as approved_at,
            created_at as withdrawable_at,
            NULL::timestamp as withdrawn_at
        FROM public.commissions
        WHERE user_id = p_user_id

        UNION ALL

        SELECT 
            id::text,
            'WITHDRAWAL' as type,
            created_at as date,
            NULL::uuid as member_id,
            NULL as job_type,
            'Withdrawal Request' as job_title,
            -amount as amount,
            status,
            created_at,
            approved_at,
            NULL as withdrawable_at,
            completed_at as withdrawn_at
        FROM public.withdrawal_requests
        WHERE user_id = p_user_id
    ),
    filtered_timeline AS (
        SELECT * FROM combined_timeline
        WHERE (p_type IS NULL OR type = p_type)
          AND (p_status IS NULL OR status = p_status)
          AND (p_date_from IS NULL OR created_at >= p_date_from::timestamp)
          AND (p_date_to IS NULL OR created_at <= p_date_to::timestamp)
    ),
    paginated AS (
        SELECT 
            id, type, date, member_id, job_type, job_title, amount, status, 
            created_at, approved_at, withdrawable_at, withdrawn_at,
            -- Build status history placeholder
            jsonb_build_array(
                jsonb_build_object('status', status, 'changed_at', created_at, 'changed_by', 'system')
            ) as status_history
        FROM filtered_timeline
        ORDER BY 
            CASE WHEN p_sort_by = 'created_at' AND p_sort_dir = 'asc' THEN created_at END ASC,
            CASE WHEN p_sort_by = 'created_at' AND p_sort_dir = 'desc' THEN created_at END DESC,
            CASE WHEN p_sort_by = 'amount' AND p_sort_dir = 'asc' THEN amount END ASC,
            CASE WHEN p_sort_by = 'amount' AND p_sort_dir = 'desc' THEN amount END DESC
        LIMIT p_limit OFFSET p_offset
    )
    SELECT jsonb_build_object(
        'success', true,
        'data', COALESCE(jsonb_agg(
            jsonb_build_object(
                'id', id,
                'type', type,
                'date', date,
                'member', NULL,
                'job_type', job_type,
                'job_title', job_title,
                'amount', amount,
                'status', status,
                'status_history', status_history,
                'created_at', created_at,
                'approved_at', approved_at,
                'withdrawable_at', withdrawable_at,
                'withdrawn_at', withdrawn_at
            )
        ), '[]'::jsonb),
        'pagination', jsonb_build_object(
            'current_page', (p_offset / p_limit) + 1,
            'total_pages', CEIL(v_total_records::numeric / p_limit),
            'total_records', v_total_records,
            'has_next', (p_offset + p_limit) < v_total_records
        )
    )
    INTO v_result
    FROM paginated;

    RETURN v_result;
END;
$$ LANGUAGE plpgsql;
