-- AIR-0244: Versioned, service-only quality policy registry for Hermes.

CREATE TABLE IF NOT EXISTS public.quality_policies (
    policy_key TEXT PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    policy JSONB NOT NULL CHECK (jsonb_typeof(policy) = 'object'),
    updated_by TEXT NOT NULL DEFAULT 'migration',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.quality_policy_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_key TEXT NOT NULL,
    version INTEGER NOT NULL,
    policy JSONB NOT NULL CHECK (jsonb_typeof(policy) = 'object'),
    updated_by TEXT NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (policy_key, version)
);

CREATE OR REPLACE FUNCTION public.record_quality_policy_version()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
BEGIN
    INSERT INTO public.quality_policy_history (policy_key, version, policy, updated_by, recorded_at)
    VALUES (NEW.policy_key, NEW.version, NEW.policy, NEW.updated_by, NEW.updated_at)
    ON CONFLICT (policy_key, version) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS quality_policy_version_history ON public.quality_policies;
CREATE TRIGGER quality_policy_version_history
AFTER INSERT OR UPDATE ON public.quality_policies
FOR EACH ROW EXECUTE FUNCTION public.record_quality_policy_version();

ALTER TABLE public.quality_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quality_policy_history ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.quality_policies FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.quality_policy_history FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.record_quality_policy_version() FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.quality_policies TO service_role;
GRANT SELECT, INSERT ON public.quality_policy_history TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.quality_policy_history_id_seq TO service_role;

DROP POLICY IF EXISTS quality_policies_service_all ON public.quality_policies;
CREATE POLICY quality_policies_service_all ON public.quality_policies
    FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS quality_policy_history_service_all ON public.quality_policy_history;
CREATE POLICY quality_policy_history_service_all ON public.quality_policy_history
    FOR ALL TO service_role USING (true) WITH CHECK (true);

INSERT INTO public.quality_policies (policy_key, version, policy, updated_by)
VALUES ('hermes_generation', 1, '{
  "schema_version": 1,
  "topic": {"enabled": true, "min_title_chars": 12},
  "plan": {"enabled": true, "min_scenes": 1, "require_media_status_ready": true},
  "script": {"enabled": true, "min_quality_score": 78, "min_hangul_chars": 1000, "max_latin_ratio": 0.05, "max_repeated_paragraph_opener": 2, "prohibit_fallback": true, "prohibit_off_category": true},
  "media": {"enabled": true, "min_image_prompt_chars": 120, "min_video_prompt_chars": 260, "max_video_prompt_scenes": 12, "required_camera_movements": 1, "require_video_guardrails": true, "prohibit_duplicate_prompts": true, "require_image_grids": true},
  "publish": {"enabled": true, "min_description_chars": 120, "require_language_match": true, "prohibit_internal_terms": true},
  "delivery": {"enabled": true, "require_all_prior_stages": true, "require_quality_report_pass": true, "block_scene_count_mismatch": true}
}'::jsonb, 'migration')
ON CONFLICT (policy_key) DO NOTHING;

ALTER TABLE public.topics_queue
    ADD COLUMN IF NOT EXISTS quality_policy_snapshot JSONB;
