-- AIR-0234: Persist upload metadata generated by AIR Worker.
--
-- script_generate now produces the same title/description/tag payload that
-- the desktop title-desc page used to create manually. Storing it on
-- topics_queue lets STD users claim a fully prepared topic without seeing or
-- running the title/description generation menu.

ALTER TABLE public.topics_queue
    ADD COLUMN IF NOT EXISTS publish_metadata JSONB;

CREATE INDEX IF NOT EXISTS idx_topics_queue_publish_metadata
    ON public.topics_queue USING GIN (publish_metadata)
    WHERE publish_metadata IS NOT NULL;
