-- =============================================================
-- Migration: AIR-0227 — Backfill NULL profiles.referral_code
--
-- ROOT CAUSE: referral_code is only auto-generated by the
-- on_auth_user_created trigger (auth-web/supabase_schema.sql:
-- handle_new_user()) at signup time. A handful of legacy accounts
-- predate this trigger and were left with referral_code = NULL,
-- while the desktop app separately generated an unrelated random
-- 6-digit code into profiles.my_referral_code for these accounts
-- (services/auth_service.py's now-removed ensure_referral_code_
-- generated() random-code path) — a code that never worked for
-- actual referral-signup validation (validate_referral_code only
-- checks referral_code) and diverged from what the web admin
-- dashboard shows. Confirmed live: exactly 3 production rows have
-- referral_code IS NULL as of this migration.
--
-- This backfills referral_code for those rows only, using the exact
-- same generation algorithm as the trigger (uppercase 8-char md5
-- substring, uniqueness-checked in a loop), so every account ends up
-- with one single, real, working referral code.
--
-- Idempotent: only touches rows where referral_code IS NULL, so a
-- second run is a no-op once the first run succeeds.
-- =============================================================

BEGIN;

DO $$
DECLARE
    r RECORD;
    new_code TEXT;
BEGIN
    FOR r IN SELECT id FROM public.profiles WHERE referral_code IS NULL LOOP
        LOOP
            new_code := upper(substr(md5(random()::text || clock_timestamp()::text || r.id::text), 1, 8));
            EXIT WHEN NOT EXISTS (SELECT 1 FROM public.profiles WHERE referral_code = new_code);
        END LOOP;

        UPDATE public.profiles SET referral_code = new_code WHERE id = r.id;
    END LOOP;
END $$;

DO $$
DECLARE
    v_remaining INTEGER;
BEGIN
    SELECT count(*) INTO v_remaining FROM public.profiles WHERE referral_code IS NULL;
    IF v_remaining <> 0 THEN
        RAISE EXCEPTION 'AIR-0227 check FAILED: % profiles still have NULL referral_code', v_remaining;
    END IF;
    RAISE NOTICE 'AIR-0227: all profiles now have a referral_code.';
END $$;

COMMIT;
