'use strict';
// Only this developer-owned static layout is HTML. All source/model data uses textContent.
titles.grounded='자료 기반 생성 · 설교';
const groundedNav=element('button','▤   자료 기반 생성');groundedNav.dataset.view='grounded';
groundedNav.onclick=()=>{view('grounded');loadReferences();};document.querySelector('aside nav').append(groundedNav);
const groundedSection=element('section');groundedSection.id='view-grounded';groundedSection.hidden=true;
groundedSection.innerHTML=`<article class="panel"><span class="tag">SOURCE-GROUNDED · ASTRA</span><h2>자료를 근거로, 해석은 구분해서.</h2><p>Google NotebookLM이나 Gemini를 호출하지 않습니다. 선택 원문을 로컬 Codex에 전달해 작성·출처 검수합니다.</p><div class="callout">YouTube URL 자막 추출, 원문 붙여넣기와 UTF-8 TXT/MD 파일을 지원합니다. PDF·웹페이지·성경 전체 자동 수집은 지원하지 않습니다. 등록된 장절·번역본의 진위는 사용자가 원본과 대조해야 합니다.</div></article>
<article class="panel"><h2>YouTube 자막 가져오기</h2><form id="youtube-form"><label>영상 URL<input id="youtube-url" type="url" required maxlength="2048" placeholder="https://www.youtube.com/watch?v=..."></label><button type="submit">자막 추출</button><p id="youtube-status" role="status" class="muted">한국어 → 영어 → 제공되는 다른 언어 순서로 가져옵니다. 자막이 없는 영상의 음성 전사는 지원하지 않습니다.</p></form></article><article class="panel"><h2>1. 자료 등록</h2><form id="reference-form"><div class="form-grid"><label>자료 제목<input name="title" required maxlength="200" placeholder="누가복음 15장 본문"></label><label>자료 종류<select name="kind"><option value="scripture">성경 본문</option><option value="commentary">주석 / 해설</option><option value="reference">일반 참고자료</option></select></label></div><div class="form-grid"><label>본문 위치 / 장절 / 페이지<input name="locator" required maxlength="300" placeholder="누가복음 15:11–32 (앞뒤 문맥 포함)"></label><label>성경 번역본<input name="translation" maxlength="100" placeholder="실제 사용한 번역본 이름"></label></div><label>파일에서 읽기 (TXT / MD, UTF-8)<input id="source-file" type="file" accept=".txt,.md"></label><label>원문 (자료당 최대 40,000자)<textarea name="text" id="source-text" required maxlength="40000" rows="8"></textarea></label><label>출처 / 사용·인용 조건 메모<input name="permission_notes" required maxlength="500" placeholder="자료 제공자와 확인한 사용 조건. 조건 미확인 자료는 게시 전에 확인하세요."></label><button class="primary" type="submit">자료를 로컬에 저장</button><p class="muted">자료 원문은 로컬 자료함에 보관됩니다. 생성 시 선택 원문이 Codex 모델 처리에 사용되며, 사용자 조건 메모가 이용 허락을 검증한 것은 아닙니다.</p></form></article>
<article class="panel"><h2>2. 이번 대본에 사용할 자료 선택</h2><div id="reference-list"></div><pre id="reference-preview" class="script" hidden></pre><p class="muted">최대 12개 · 합계 80,000자. 초과하면 나눠 작업해야 하며 원문을 자동 절단하지 않습니다.</p></article>
<article class="panel"><h2>3. 자료 기반 대본 작성</h2><form id="grounded-form"><label>대본 제목 / 주제<input name="title" required maxlength="200" placeholder="돌아온 아들을 맞이하는 아버지의 마음"></label><div class="form-grid"><label>모드<select name="grounded_type"><option value="sermon">성경 기반 설교</option><option value="education">자료 기반 교육·해설</option></select></label><label>대상 청중<input name="audience" required maxlength="200" value="시니어 성도"></label><label>분량 (분)<input name="duration_minutes" type="number" min="1" max="60" value="15"></label></div><label>다룰 본문 범위 / 자료 범위<input name="passage" required maxlength="200" placeholder="등록 자료 중 사용할 장절과 주변 문맥"></label><label>교단·신학적 관점 / 해설 관점<input name="perspective" required maxlength="500" placeholder="원하는 관점 또는 교단 공통의 본문 해설, 논쟁적 해석은 유보 등"></label><label>추가 요청<textarea name="notes" maxlength="4000" rows="3"></textarea></label><div class="callout">성경 인용 · 해석 · 창작 예화 · 적용 · 사실을 구분하고 인용 근거를 저장합니다. AI 검수는 신학적 정답 보증이 아닙니다. 완성 초안을 읽고 사용자가 승인해야 합니다.</div><button class="primary" type="submit">Astra 자료 기반 대본 생성</button></form></article>`;
document.querySelector('main').insertBefore(groundedSection,document.querySelector('footer'));
async function loadReferences(){try{const data=await api('references');const list=$('reference-list');const selected=new Set([...list.querySelectorAll('input:checked')].map(x=>x.value));list.replaceChildren();for(const source of data.items){const row=element('div',undefined,'job'),label=element('label');label.style.margin='0';const check=element('input');check.type='checkbox';check.value=source.id;check.style.width='auto';check.style.display='inline';check.checked=selected.has(source.id);label.append(check,document.createTextNode(' '+source.title+' · '+source.kind+' · '+source.locator+' · '+(source.translation||'번역본 없음')+' · '+source.characters+'자'));row.append(label);const read=element('button','원문 읽기');read.type='button';read.onclick=async()=>{try{const full=await api('references/'+source.id);$('reference-preview').textContent=full.title+'\n'+full.locator+' / '+full.translation+'\n사용 조건: '+full.permission_notes+'\n\n'+full.text;$('reference-preview').hidden=false;}catch(e){error(e.message);}};row.append(read);list.append(row);}if(!data.items.length)list.append(element('p','등록 자료가 없습니다. 사용할 성경 본문이나 참고자료를 먼저 등록하세요.'));}catch(e){error(e.message);}}
$('source-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(!/\.(txt|md)$/i.test(file.name)||file.size>200000)throw new Error('200KB 이하 UTF-8 TXT/MD 파일만 읽습니다.');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());if(text.length>40000)throw new Error('40,000자를 초과했습니다. 원문을 나눠 등록하세요.');$('source-text').value=text;}catch(e){error(e.message);}};
$('reference-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const saved=await api('references',Object.fromEntries(new FormData(e.target)));notice('원문과 출처 정보를 로컬 자료함에 저장했습니다.');e.target.reset();await loadReferences();const checkbox=[...$('reference-list').querySelectorAll('input')].find(x=>x.value===saved.id);if(checkbox)checkbox.checked=true;}catch(e){error(e.message);}finally{button.disabled=false;}};
$('grounded-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const source_ids=[...$('reference-list').querySelectorAll('input:checked')].map(x=>x.value);if(!source_ids.length){error('사용할 자료를 선택하세요.');return;}if(!confirm('선택 자료로 Astra 대본 작성·출처 검수를 실행할까요? Codex 사용량이 발생하고 운영 대본은 변경하지 않습니다.'))return;const form=Object.fromEntries(new FormData(e.target));await start({...form,mode:'grounded',source_ids,duration_minutes:Number(form.duration_minutes)});};
const citationPanel=element('div');$('result').append(citationPanel);
if(location.hash==='#grounded')groundedNav.click();
window.renderGroundedResult=data=>{citationPanel.replaceChildren();if(data.job.mode==='topics'||!data.sources?.length)return;citationPanel.append(element('h3','인용 근거 · 자료 원문 대조'));for(const section of data.citations){const block=element('details');block.append(element('summary','씬 '+section.scene_order+' · '+section.kind));for(const citation of section.citations||[]){const source=data.sources.find(s=>s.id===citation.source_id);block.append(element('pre','대본: '+citation.claim+'\n근거: '+citation.quote+'\n출처: '+(source?.title||citation.source_id)+' / '+citation.locator+' / '+citation.translation,'script'));}citationPanel.append(block);}const originals=element('details');originals.append(element('summary','이 작업에 고정한 원본 자료 보기'));for(const source of data.sources)originals.append(element('pre',source.title+'\n'+source.locator+' / '+source.translation+'\nSHA256: '+source.sha256+'\n\n'+source.text,'script'));citationPanel.append(originals,element('p','출처 검사: '+(data.grounding_report?.verdict||'미확인')+' · 사용자 본문/신학 검토는 별도입니다.','muted'));};

$('youtube-form').onsubmit=async e=>{
  e.preventDefault();
  const form=$('reference-form');
  if(form.elements.text.value.trim()&&!confirm('작성 중인 자료를 추출한 자막으로 바꿀까요?'))return;
  const button=e.target.querySelector('button');button.disabled=true;
  const fields=[...form.elements];fields.forEach(field=>field.disabled=true);
  $('youtube-status').textContent='YouTube 자막을 가져오는 중…';error('');
  try{
    const data=await api('youtube-transcript',{url:$('youtube-url').value});
    form.elements.title.value=data.title;form.elements.kind.value='reference';
    form.elements.locator.value=data.url;form.elements.translation.value='';
    form.elements.text.value=data.text;form.elements.permission_notes.value='YouTube 자막 · '+(data.is_generated?'자동 생성':'제공 자막')+' · '+data.language+' · 사용 조건 미확인';
    $('youtube-status').textContent=data.text.length.toLocaleString()+'자 추출 완료 · '+data.language+' · '+(data.is_generated?'자동 생성 자막':'제공 자막');
    notice('추출한 자막과 출처를 확인한 뒤 자료를 로컬에 저장하세요.');
    $('source-file').value='';
  }catch(e){$('youtube-status').textContent='추출 실패 · 기존 자료는 유지됩니다.';error(e.message);}
  finally{button.disabled=false;fields.forEach(field=>field.disabled=false);}
};
