import os
from moviepy.editor import ImageClip, ColorClip, CompositeVideoClip

def test_moviepy_wrapping():
    # Use the image generated by repro_wrapping.py
    img_path = "debug_wrapping.png"
    if not os.path.exists(img_path):
        print("Please run repro_wrapping.py first to generate debug_wrapping.png")
        return

    # Mock Video Dimensions (Portrait 1080x1920)
    w = 1080
    h = 1920
    
    # Create black background
    bg_clip = ColorClip(size=(w, h), color=(0,0,0), duration=5)
    
    # Load subtitle image
    txt_clip = ImageClip(img_path)
    
    # Position like in video_service.py
    # txt_clip = txt_clip.set_position(("center", "bottom")) 
    
    # Let's try to verify if 'bottom' clips it
    final_clip = CompositeVideoClip([bg_clip, txt_clip.set_position(("center", "bottom"))])
    
    # Save a frame
    final_clip.save_frame("debug_moviepy_bottom.png", t=1)
    print("Saved debug_moviepy_bottom.png")
    
    # Try with margin
    final_clip_margin = CompositeVideoClip([bg_clip, txt_clip.set_position(("center", h - txt_clip.h - 150))])
    final_clip_margin.save_frame("debug_moviepy_margin.png", t=1)
    print("Saved debug_moviepy_margin.png")

if __name__ == "__main__":
    test_moviepy_wrapping()
