'use client'
import {useCallback,useEffect,useState} from 'react'
type AdminFetch=(input:RequestInfo | URL,init?:RequestInit)=>Promise<Response>
const box='rounded-2xl border border-white/10 bg-[#0f172a]/60 p-5 space-y-3'
const input='w-full rounded-lg border border-white/20 bg-black/30 p-3 text-white'
const button='rounded-lg border border-white/20 px-4 py-2 text-sm disabled:opacity-40'
const statuses:Record<string,string>={pending:'승인 대기',approved:'적용 중',rejected:'반려',retired:'비활성화',queued:'대기',running:'실행 중',failed:'실패',awaiting_approval:'대본 검토 대기',approved_pending_repair:'승인·적용 대기',completed:'완료',interrupted:'중단'}
export default function ScriptOperationsPanel({adminFetch,mode}:{adminFetch:AdminFetch;mode:'worker'|'guidelines'}){
    const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
    const [draft,setDraft]=useState({title:'',issue:'',instruction:'',category:'',language:'',source_job_id:''}),[notes,setNotes]=useState<Record<string,string>>({})
    const load=useCallback(async()=>{try{const res=await adminFetch(mode==='worker'?'/api/admin/codex-worker':'/api/admin/script-guidelines',{cache:'no-store'});const body=await res.json();if(!res.ok)throw Error(body.error);setData(body);setError('')}catch(e:any){setError(e.message || '조회 실패')}},[adminFetch,mode])
    useEffect(()=>{setData(null);void load();if(mode==='worker'){const t=setInterval(()=>void load(),15000);return()=>clearInterval(t)}},[load,mode])
    const action=async(body:any)=>{if(busy)return;setBusy(true);try{const res=await adminFetch('/api/admin/script-guidelines',{method:'POST',body:JSON.stringify(body)});const result=await res.json();if(!res.ok)throw Error(result.error);if(body.action==='propose')setDraft({title:'',issue:'',instruction:'',category:'',language:'',source_job_id:''});await load()}catch(e:any){setError(e.message || '저장 실패')}finally{setBusy(false)}}
    return <div className="space-y-5 text-white"><div className={box}><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-bold">{mode==='worker'?'현재 대본워커':'대본 지침 개선'}</h2><button className={button} onClick={()=>void load()}>새로고침</button></div>
        <p className="text-sm text-gray-400">{mode==='worker'?'현재 로컬 Codex 작업의 Database 기록입니다. 작업 상태와 컴퓨터의 온라인 여부는 별개입니다. 생성·리페어는 워커가 설치된 컴퓨터에서 실행합니다.':'문제 기록 → 지침 승인 → 다음 대본 적용 → 검수 결과 확인. 승인된 지침만 일치하는 카테고리·언어의 새 작업에 적용됩니다.'}</p>
        <a className="inline-block text-blue-300 underline" href="http://127.0.0.1:3003/" target="_blank" rel="noopener noreferrer">이 컴퓨터의 대본워커 열기</a>
        {mode==='guidelines'&&<p className="text-xs text-gray-400">Notion 복사는 로컬 워커에서 선택적으로 실행합니다. 기준 저장소는 Database입니다.</p>}</div>
        {error&&<p role="alert" className="text-red-300">{error}</p>}{!data&&!error&&<p>불러오는 중…</p>}
        {mode==='worker'&&data&&<><p>현재 대기·실행 작업: {data.active_count}건</p>{!data.jobs.length&&<p>저장된 작업이 없습니다.</p>}{data.jobs.map((j:any)=><article key={j.id} className={box}><h3 className="font-bold">{j.title} · {statuses[j.status] || j.status}</h3><p className="text-sm text-gray-400">{j.job_record?.stage} · {new Date(j.updated_at*1000).toLocaleString()}</p><p className="text-xs break-all">작업 ID: {j.id}</p></article>)}</>}
        {mode==='guidelines'&&<><form className={box} onSubmit={e=>{e.preventDefault();void action({action:'propose',...draft})}}><h3 className="font-bold">개선안 등록</h3>
        {([['title','개선안 제목',200],['issue','발견한 문제·수정/반려 사유',4000],['instruction','다음 대본에 적용할 지침',4000],['category','카테고리 (비우면 전체)',80],['source_job_id','관련 작업 ID (선택)',32]] as const).map(([key,label,max])=><label className="block space-y-1" key={key}><span>{label}</span>{['issue','instruction'].includes(key)?<textarea className={input} required maxLength={max} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>:<input className={input} required={key==='title'} maxLength={max} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}</label>)}
        <label className="block">대본 언어<select className={input} value={draft.language} onChange={e=>setDraft({...draft,language:e.target.value})}>{[['','전체'],['ko','한국어'],['ja','일본어'],['en','영어'],['es','스페인어'],['vi','베트남어'],['th','태국어']].map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label><button disabled={busy} className={button}>개선안 저장 · 승인 대기</button></form>
        <h3 className="font-bold">지침 버전·검토 이력</h3>{data?.items.length===0&&<p>등록된 개선안이 없습니다.</p>}{data?.items.map((r:any)=><article className={box} key={r.id}><h3 className="font-bold">v{r.version} · {r.title} · {statuses[r.status]}</h3><p>범위: {r.category || '전체 카테고리'} / {r.language || '전체 언어'}</p><p className="whitespace-pre-wrap">문제: {r.issue}</p><p className="whitespace-pre-wrap">지침: {r.instruction}</p><p>검토 의견: {r.review_note || '없음'}</p>
        {['pending','approved'].includes(r.status)&&<><textarea aria-label={`v${r.version} 검토 사유`} className={input} maxLength={1000} placeholder="검토 사유 (반려·비활성화 시 필수)" value={notes[r.id] || ''} onChange={e=>setNotes({...notes,[r.id]:e.target.value})}/><div className="flex flex-wrap gap-2">{(r.status==='pending'?[['approve','승인 · 다음 작업부터 적용'],['reject','반려']]:[['retire','비활성화']]).map(([value,text])=><button className={button} key={value} disabled={busy} onClick={()=>void action({action:value,id:r.id,note:notes[r.id] || ''})}>{text}</button>)}</div></>}</article>)}
        <h3 className="font-bold">적용 결과·최근 검수</h3><p className="text-sm text-gray-400">자동 검수 점수는 참고 자료입니다. 실제 대본 확인과 함께 개선 효과를 판단하세요.</p>{data?.outcomes.map((r:any)=><details key={r.job_id} className={box}><summary>{r.title} · {statuses[r.status] || r.status} · 적용: {r.applied_versions.map((v:any)=>'v'+v.version).join(', ') || '없음'}</summary><pre className="whitespace-pre-wrap break-words text-xs">{JSON.stringify(r.evaluation,null,2)}</pre></details>)}</>}
    </div>
}
